use strict;
use warnings;
use Git::Repository;
use YAML;
use Data::Dumper;

if (@ARGV != 1) {
	die "Usage: $0 <watch | build>"
}

my ($action) = @ARGV;

watch() if $action eq 'watch';
build() if $action eq 'build';

sub watch {
	print "Watching...\n";

}

sub build {
	print "Building...\n";
	update_data();
}

sub update_data {
	print "Updating data...\n";

	my $repo = Git::Repository->new();
	my $rev = $repo->run('rev-parse', '--verify', 'HEAD');
	my $shortrev = $repo->run('rev-parse', '--short', 'HEAD');

	my $data = {
		rev => $rev,
		shortrev => $shortrev
	};

	open(my $fh, '>', './.data.yml');
	print $fh "# This file is automatically generated. Data will be overwritten by build.pl script\n";
	print $fh Dump $data;
	close $fh;
}
